// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: recognition.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Recognition_Recognize_FullMethodName = "/recognition.Recognition/Recognize"
)

// RecognitionClient is the client API for Recognition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecognitionClient interface {
	Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
}

type recognitionClient struct {
	cc grpc.ClientConnInterface
}

func NewRecognitionClient(cc grpc.ClientConnInterface) RecognitionClient {
	return &recognitionClient{cc}
}

func (c *recognitionClient) Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeResponse)
	err := c.cc.Invoke(ctx, Recognition_Recognize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecognitionServer is the server API for Recognition service.
// All implementations must embed UnimplementedRecognitionServer
// for forward compatibility.
type RecognitionServer interface {
	Recognize(context.Context, *RecognizeRequest) (*RecognizeResponse, error)
	mustEmbedUnimplementedRecognitionServer()
}

// UnimplementedRecognitionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecognitionServer struct{}

func (UnimplementedRecognitionServer) Recognize(context.Context, *RecognizeRequest) (*RecognizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recognize not implemented")
}
func (UnimplementedRecognitionServer) mustEmbedUnimplementedRecognitionServer() {}
func (UnimplementedRecognitionServer) testEmbeddedByValue()                     {}

// UnsafeRecognitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecognitionServer will
// result in compilation errors.
type UnsafeRecognitionServer interface {
	mustEmbedUnimplementedRecognitionServer()
}

func RegisterRecognitionServer(s grpc.ServiceRegistrar, srv RecognitionServer) {
	// If the following call pancis, it indicates UnimplementedRecognitionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Recognition_ServiceDesc, srv)
}

func _Recognition_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recognition_Recognize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServer).Recognize(ctx, req.(*RecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recognition_ServiceDesc is the grpc.ServiceDesc for Recognition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recognition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recognition.Recognition",
	HandlerType: (*RecognitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recognize",
			Handler:    _Recognition_Recognize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recognition.proto",
}
